services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dwifahriza45/we-saving-app:dev
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWTSecret=${JWTSecret}
      - PORT=${PORT:-8080}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - appnet
    restart: on-failure

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Jakarta
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/migrations
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
